# Generated by Django 4.2.7 on 2023-11-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Task',
        ),
    ]
